{{- if .Values.ingressGrpc.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "provider.fullname" . }}
  labels:
    {{- include "provider.labels" . | nindent 4 }}
  {{- with .Values.ingressGrpc.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingressGrpc.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- if .Values.ingressGrpc.tls }}
  tls:
    - hosts:
      {{- range $itemKey, $itemValue := $.Values.chains }}
        - "{{ $itemKey | lower }}.{{ include "provider.domain" $ }}"
      {{- end }}
      secretName: provider-grpc-tls
  {{- end }}
  rules:
    {{- range $itemKey, $itemValue := $.Values.chains }}
    - host: "{{ $itemKey | lower }}.{{ include "provider.domain" $ }}"
      http:
        paths:
          - path: {{ $.Values.ingressGrpc.path }}
            pathType: {{ $.Values.ingressGrpc.pathType }}
            backend:
              service:
                name: {{ $itemKey | lower }}-{{ include "provider.fullname" $ }}
                port:
                  name: grpc
    {{- end }}
{{- end }}