{{- range $itemKey, $itemValue := $.Values.chains }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name:  {{ $itemKey | lower }}-{{ include "provider.fullname" $ }}
  labels:
    {{- include "provider.labels" $ | nindent 4 }}
    app.lavanet.io/chain: {{ $itemKey | lower }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
  {{- range $itemValue.persistence.accessModes }}
    - {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ $itemValue.persistence.size | quote }}
{{- end }}
