{{- range $itemKey, $itemValue := $.Values.chains }}
{{- if (empty $itemValue.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $itemKey | lower }}-{{ include "provider.fullname" $ }}
  labels:
    {{- include "provider.labels" $ | nindent 4 }}
    app.kubernetes.io/chain: {{ $itemKey | lower }}
data:
  config.yaml: |
    endpoints:
    {{- range $interfaceEntry := $itemValue.interfaces }}
      - chain-id: {{ $itemKey | upper }}
        api-interface: {{ $interfaceEntry.interface }}
        disable_tls: {{ $interfaceEntry.disable_tls | default "false" }}
        network-address: 0.0.0.0:{{ $interfaceEntry.port }}
        node-urls:
        {{- range $node := $interfaceEntry.nodes }}
          - url: {{ $node.endpoint | quote }}
          {{- if ne $node.type "full" }}
            {{- $skipVerifications := default "" $node.skipVerifications }}
            {{- if eq $skipVerifications "pruning" }}
            skip-verifications:
              - pruning
            {{- end }}
            addons:
              - {{ $node.type }}
          {{- end }}
        {{- end }}    
    {{- end }}
    {{- if $itemValue.metrics.enabled }}
    metrics-listen-address: "0.0.0.0:{{ $itemValue.metrics.port }}"
    {{- end }}
{{- end }}
{{- end }}
