{{- range $itemKey, $itemValue := $.Values.chains }}
{{- if not $itemValue.existingConfigSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $itemKey | lower }}-{{ include "provider.fullname" $ }}
  labels:
    {{- include "provider.labels" $ | nindent 4 }}
    app.lavanet.io/chain: {{ $itemKey | lower }}
data:
  config.yml: {{ include "configYaml" (dict "itemKey" $itemKey "itemValue" $itemValue "root" $) | b64enc }}
{{- end }}
{{- end }}

{{- define "configYaml" }}
endpoints:
{{- range $interfaceEntry := .itemValue.interfaces }}
  - chain-id: {{ $.itemKey | upper }}
    api-interface: {{ $interfaceEntry.interface }}
    network-address:
      address: 0.0.0.0:{{ $.root.Values.service.port }}
      disable-tls: {{ $interfaceEntry.disableTLS | default "false" }}
    node-urls:
    {{- range $node := $interfaceEntry.nodes }}
      - url: {{ $node.endpoint | quote }}
      {{- if ne $node.type "full" }}
        {{- $skipVerifications := default "" $node.skipVerifications }}
        {{- if eq $skipVerifications "pruning" }}
        skip-verifications:
          - pruning
        {{- end }}
        addons:
          - {{ $node.type }}
      {{- end }}
    {{- end }}
{{- end }}
{{- if $.root.Values.metrics.enabled }}
metrics-listen-address: "0.0.0.0:{{ $.root.Values.metrics.port }}"
{{- end }}
{{- end }}
