{{- range $itemKey, $itemValue := $.Values.chains }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $itemKey | lower }}-{{ include "provider.fullname" $ }}
  labels:
    {{- include "provider.labels" $ | nindent 4 }}
    app.lavanet.io/chain: {{ $itemKey | lower }}
spec:
  type: {{ $.Values.service.type }}
  ports:
    - port: {{ $.Values.service.port }}
      targetPort: provider
      protocol: TCP
      name: provider
  {{- if $.Values.metrics.enabled }}
    - port: {{ $.Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  {{- end }}
  selector:
    {{- include "provider.selectorLabels" $ | nindent 4 }}
    app.lavanet.io/chain: {{ $itemKey | lower }}
{{- end }}
