repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes

  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.23
    hooks:
      - id: helmlint

  - repo: https://github.com/norwoodj/helm-docs
    rev: "v1.14.2"
    hooks:
      - id: helm-docs-container
        args:
          - --chart-search-root=charts

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
        exclude: ".*provider/README.md|.*consumer/README.md|.*cache/README.md"
      - id: trailing-whitespace
        exclude: ".*provider/README.md|.*consumer/README.md|.*cache/README.md"
      - id: detect-private-key
      - id: check-merge-conflict
      - id: check-added-large-files
