{{- range $itemKey, $itemValue := $.Values.chains }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $itemKey | lower }}-{{ include "consumer.fullname" $ }}
  labels:
    {{- include "consumer.labels" $ | nindent 4 }}
data:
  config.yml: |
    endpoints:
    {{- range $interfaceEntry := $itemValue.interfaces }}
      - chain-id: {{ $itemKey | upper }}
        api-interface: {{ $interfaceEntry.interface }}
        network-address: 0.0.0.0:{{ $interfaceEntry.port }}
    {{- end }}
    static-providers:
    {{- range $interfaceEntry := $itemValue.interfaces }}
    {{- if $interfaceEntry.staticProviders }}
      - chain-id: {{ $itemKey | upper }}
        api-interface: {{ $interfaceEntry.interface }}
        node-urls:
        {{- range $staticProvider := $interfaceEntry.staticProviders }}
          - url: {{ $staticProvider.url }}
        {{- end }}
    {{- end }}    
    {{- end }}
    metrics-listen-address: "0.0.0.0:{{ $.Values.metrics.port }}"
{{- end }}
