{{- if .Values.ingressGrpc.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "consumer.fullname" . }}-grpc
  labels:
    {{- include "consumer.labels" . | nindent 4 }}
  {{- with .Values.ingressGrpc.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingressGrpc.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- if .Values.ingressGrpc.tls }}
  tls:
    - hosts:
      {{- range $itemKey, $itemValue := $.Values.chains }}
      {{- range $interfaceEntry := $itemValue.interfaces }}
      {{- if (eq ($interfaceEntry.interface | lower) "grpc") }}
        - "{{ $itemKey | lower }}-{{ $interfaceEntry.interface | lower }}.{{ include "consumer.domain" $ }}"
      {{- end }}
      {{- end }}
      {{- end }}
      secretName: consumer-grpc-tls
  {{- end }}
  rules:
    {{- range $itemKey, $itemValue := $.Values.chains }}
    {{- range $interfaceEntry := $itemValue.interfaces }}
    {{- if (eq ($interfaceEntry.interface | lower) "grpc") }}
    - host: "{{ $itemKey | lower }}-{{ $interfaceEntry.interface | lower }}.{{ include "consumer.domain" $ }}"
      http:
        paths:
          - path: {{ $.Values.ingressGrpc.path }}
            pathType: {{ $.Values.ingressGrpc.pathType }}
            backend:
              service:
                name: {{ $itemKey | lower }}-{{ include "consumer.fullname" $ }}
                port:
                  name: {{ $interfaceEntry.interface | lower }}
    {{- end }}
    {{- end }}
    {{- end }}
{{- end }}
