apiVersion: v2
name: consumer
description: Lava consumer helm chart
icon: https://github.com/lavanet/helm-charts/blob/main/docs/logo/logo.png?raw=true
type: application
version: 0.2.7
appVersion: "v2.2.5"
